apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: prod-clusters
  namespace: openshift-cert-manager-operator
spec:
  clusterSelector:
    matchLabels:
      environment: prod
